const { mongoose, Schema } = require("mongoose");

const ProductSchema = new Schema({
  name: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  },
  categoryName: {
    type: String,
    required: true,
  },
  photo: {
    type: String,
    required: true,
  },
  weight: {
    type: Number,
    required: true,
  },
  calorie: {
    type: Number,
    required: true,
  },
  protein: {
    type: Number,
    required: true,
  },
  switchWith: {
    type: String,
  },
  isSelected: {
    type: Boolean,
  },
});
const Products = [
  {
    name: "Oats",
    weight: "0.35",
    cal: 1361,
    protein: 10.9,
    category: "Staple & Non Grains",
  },
  {
    name: "Boiled Rice",
    weight: "5",
    cal: 6500,
    protein: 2.7,
    category: "Staple & Non Grains",
  },
  {
    name: "Wheat Flour",
    weight: "2",
    cal: 7280,
    protein: 2.7,
    category: "Staple & Non Grains",
  },
  {
    name: "Broken Wheat",
    weight: "0.5",
    cal: 1750,
    protein: 12.5,
    category: "Staple & Non Grains",
  },
  {
    name: "Semolina",
    weight: "0.5",
    cal: 360,
    protein: 11,
    category: "Staple & Non Grains",
  },
  {
    name: "Cornflakes",
    weight: "0.35",
    cal: 1249,
    protein: 8,
    category: "Staple & Non Grains",
  },
  {
    name: "Flattened Rice",
    weight: "0.5",
    cal: 1850,
    protein: 6.2,
    category: "Staple & Non Grains",
  },
  {
    name: "Vermicelli",
    weight: "0.5",
    cal: 1760,
    protein: 0,
    category: "Staple & Non Grains",
  },
  {
    name: "Refined Wheat Flour",
    weight: "2",
    cal: 7280,
    protein: 10,
    category: "Staple & Non Grains",
  },
  {
    name: "Split Yellow Lentil",
    weight: "0.5",
    cal: 1695,
    protein: 24,
    category: "Pulses & Legumes",
  },
  {
    name: "Split Yellow Pea",
    weight: "0.5",
    cal: 1760,
    protein: 22,
    category: "Pulses & Legumes",
  },
  {
    name: "Whole Dried Yellow Peas",
    weight: "0.5",
    cal: 1800,
    protein: 21,
    category: "Pulses & Legumes",
  },
  {
    name: "Red Lentil",
    weight: "0.5",
    cal: 1800,
    protein: 25,
    category: "Pulses & Legumes",
  },
  {
    name: "Split Bengal Gram",
    weight: "0.5",
    cal: 1820,
    protein: 20.8,
    category: "Pulses & Legumes",
  },
  {
    name: "Whole Chickpeas",
    weight: "0.5",
    cal: 1820,
    protein: 19,
    category: "Pulses & Legumes",
  },
  {
    name: "Mustard Oil",
    weight: "0.5",
    cal: 4420,
    protein: 0,
    category: "Oil",
  },
  { name: "Ghee", weight: "0.1", cal: 790, protein: 0, category: "Oil" },
  { name: "White Oil", weight: "0.5", cal: 4420, protein: 0, category: "Oil" },
  {
    name: "Edible Fat Spread",
    weight: "0.1",
    cal: 617,
    protein: 0,
    category: "Oil",
  },
  {
    name: "Pasta",
    weight: "0.35",
    cal: 1295,
    protein: 13,
    category: "Pasta & Noodles",
  },
  {
    name: "Noodles",
    weight: "0.35",
    cal: 402,
    protein: 8,
    category: "Pasta & Noodles",
  },
  {
    name: "Salt Lite",
    weight: "0.35",
    cal: 0,
    protein: 0,
    category: "Essential Items",
  },
  {
    name: "Sugar",
    weight: "0.25",
    cal: 967,
    protein: 0,
    category: "Essential Items",
  },
  {
    name: "Sugar Free Biscuit",
    weight: "0.25",
    cal: 1177,
    protein: 3,
    category: "Essential Items",
  },
  {
    name: "Premium Tea",
    weight: "0.05",
    cal: 0,
    protein: 0,
    category: "Essential Items",
  },
  {
    name: "Jaggery Cubes",
    weight: "0.25",
    cal: 957,
    protein: 0,
    category: "Essential Items",
  },
  {
    name: "Poppy Seeds",
    weight: "0.025",
    cal: 131.3,
    protein: 18,
    category: "Condiments",
  },
  {
    name: "Spices Whole",
    weight: "0.025",
    cal: 82.5,
    protein: 0,
    category: "Condiments",
  },
  {
    name: "Spices Powder",
    weight: "0.1",
    cal: 350,
    protein: 0,
    category: "Condiments",
  },
  {
    name: "Sauce & Ketchup",
    weight: "0.1",
    cal: 120,
    protein: 0,
    category: "Condiments",
  },
  {
    name: "Mix Nuts",
    weight: "0.1",
    cal: 607,
    protein: 21,
    category: "Miscellaneous Item",
  },
  {
    name: "Dry Fruits",
    weight: "0.1",
    cal: 325,
    protein: 2.5,
    category: "Miscellaneous Item",
  },
  {
    name: "Gram Flour",
    weight: "0.1",
    cal: 387,
    protein: 22,
    category: "Miscellaneous Item",
  },
  {
    name: "Corn Flour",
    weight: "0.1",
    cal: 310,
    protein: 0,
    category: "Miscellaneous Item",
  },
  {
    name: "Raw Peanuts",
    weight: "0.1",
    cal: 567,
    protein: 26,
    category: "Miscellaneous Item",
  },
  {
    name: "Whole Black Bengal Gram",
    weight: "0.2",
    cal: 728,
    protein: 20,
    category: "Miscellaneous Item",
  },
  {
    name: "Soya Chunks",
    weight: "0.2",
    cal: 672,
    protein: 52,
    category: "Miscellaneous Item",
  },
  {
    name: "Egg",
    weight: "0.1",
    cal: 450,
    protein: 12,
    category: "Root Vegetables",
  },
  {
    name: "Onion",
    weight: "0.25",
    cal: 500,
    protein: 1,
    category: "Root Vegetables",
  },
  {
    name: "Potato",
    weight: "0.5",
    cal: 1925,
    protein: 2,
    category: "Root Vegetables",
  },
  {
    name: "Ginger",
    weight: "0.05",
    cal: 200,
    protein: 1.8,
    category: "Root Vegetables",
  },
  {
    name: "Tomato",
    weight: "0.25",
    cal: 225,
    protein: 1,
    category: "Root Vegetables",
  },
  {
    name: "Garlic",
    weight: "0.05",
    cal: 277.5,
    protein: 6.4,
    category: "Root Vegetables",
  },
  {
    name: "Fish",
    weight: "0.25",
    cal: 2750,
    protein: 1.5,
    category: "Fresh Produce",
  },
  {
    name: "Chicken Meat",
    weight: "0.25",
    cal: 2750,
    protein: 37.5,
    category: "Fresh Produce",
  },
  {
    name: "Paneer",
    weight: "0.25",
    cal: 2750,
    protein: 18,
    category: "Fresh Produce",
  },
  {
    name: "Mushroom",
    weight: "0.25",
    cal: 2750,
    protein: 3,
    category: "Fresh Produce",
  },
];

const Product = mongoose.model("Product", ProductSchema);

module.exports = Product;
